apiVersion: v1
kind: Service
metadata:
  name: appointment-management-app-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
