apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: appt-app
  name: springboot-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: appt-app
  template:
    metadata:
      labels:
        app: appt-app
    spec:
      containers:
        - name: my-appt-app
          image: 626635406112.dkr.ecr.us-east-2.amazonaws.com/appointment-management-ecr-repo
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              name: http
              protocol: TCP
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: appt-app
    k8s-app: appt-app
  name: appt-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8085
  type: LoadBalancer
  selector:
    app: appt-app